In [1]:
import numpy

In [2]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


In [4]:
b = numpy.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
print("a.shape", a.shape)
print("b.shape", b.shape)

a.shape (4,)
b.shape (2, 3)


In [6]:
print(a.size)
print(b.size)

4
6


In [7]:
print(numpy.arange(5))

[0 1 2 3 4]


In [8]:
print(numpy.arange(1,10,2))

[1 3 5 7 9]


In [9]:
print(numpy.arange(6))

[0 1 2 3 4 5]


In [10]:
print(numpy.arange(6).reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [11]:
print(numpy.linspace(2.0,3.0,num=5))

[2.   2.25 2.5  2.75 3.  ]


In [12]:
print(numpy.linspace(2.0,3.0,num=5,endpoint=False))

[2.  2.2 2.4 2.6 2.8]


In [2]:
import numpy

In [3]:
a,step = numpy.linspace(2.0,3.0,num=5, retstep=True)
print(a)

[2.   2.25 2.5  2.75 3.  ]


In [4]:
print(step)

0.25


In [5]:
print(numpy.ones(5))

[1. 1. 1. 1. 1.]


In [7]:
print(numpy.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
print(numpy.zeros(5))

[0. 0. 0. 0. 0.]


In [9]:
print(numpy.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
print(numpy.eye(2))

[[1. 0.]
 [0. 1.]]


In [12]:
a = numpy.array([2,4,6])
print(numpy.diag(a))

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [14]:
a = numpy.array([[2,4],[6,8]])
print(a)

[[2 4]
 [6 8]]


In [15]:
print(numpy.diag(a))

[2 8]


In [16]:
a = numpy.arange(5)
print(a)

[0 1 2 3 4]


In [17]:
print(a.dtype)

int64


In [18]:
a = numpy.arange(5, dtype=float)

In [19]:
print(a)

[0. 1. 2. 3. 4.]


In [20]:
ao = numpy.array([[1],[2,3]])
print(ao)

[list([1]) list([2, 3])]


In [21]:
print(ao.dtype)

object


In [22]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


In [23]:
print(a + 1)

[1 2 3 4]


In [24]:
print(a * 2)

[0 2 4 6]


In [25]:
a = numpy.array([1,2,3])
b = numpy.array([4,5,6])
print(a + b)

[5 7 9]


In [26]:
print( a * b)

[ 4 10 18]


In [27]:
print( a == b)

[False False False]


In [28]:
print(numpy.array_equal(a,b))

False


In [29]:
print(a > b)

[False False False]


In [30]:
print( a < b)

[ True  True  True]


In [31]:
a = numpy.array([1,3,5,7])
print(a)

[1 3 5 7]


In [32]:
print(a[1])

3


In [33]:
b  = numpy.arange(6).reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [35]:
print(b.shape
     ) 

(2, 3)


In [36]:
print(b[1])

[3 4 5]


In [37]:
print(b[1,1])

4


In [38]:
print(b.shape)

(2, 3)


In [39]:
print(a[1:3])

[3 5]


In [40]:
print(a[1:])

[3 5 7]


In [41]:
print(a[::-1])

[7 5 3 1]


In [42]:
print(a)
a[2:] = numpy.array([10,14])

[1 3 5 7]


In [43]:
print(a)

[ 1  3 10 14]


In [46]:
b = numpy.arange(9).reshape(3,3)
print(b)
print()
print(b[1:,1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[4 5]
 [7 8]]


In [47]:
b = numpy.arange(6).reshape(2,3)
print(b)
print()
print(b[1,:])
print(b[1])
print(b[:,1])

[[0 1 2]
 [3 4 5]]

[3 4 5]
[3 4 5]
[1 4]


In [48]:
a = numpy.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [49]:
print(a % 3 == 0)

[ True False False  True False False  True False False  True False False
  True False False]


In [50]:
mask = (a % 3 == 0)
print(mask)

[ True False False  True False False  True False False  True False False
  True False False]


In [51]:
print(a[mask])

[ 0  3  6  9 12]


In [52]:
a[mask] = -1
print(a)

[-1  1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14]


In [53]:
lst = list(range(0,15,2))
print(lst)

[0, 2, 4, 6, 8, 10, 12, 14]


In [56]:
print(a[lst])

[-1  2  4 -1  8 10 -1 14]


In [57]:
print(a)

[-1  1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14]


In [58]:
print(a[numpy.arange(0,15,2)])

[-1  2  4 -1  8 10 -1 14]


In [59]:
a = numpy.arange(1,5)
print(a)

[1 2 3 4]


In [60]:
print(numpy.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [61]:
print(numpy.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [62]:
print(numpy.log(a))

[0.         0.69314718 1.09861229 1.38629436]


In [63]:
a = numpy.array([1,2,3,4])
print(a)

[1 2 3 4]


In [64]:
print(numpy.sum(a))

10


In [65]:
print(numpy.max(a))

4


In [66]:
print(numpy.argmax(a))

3


In [67]:
print(a[numpy.argmax(a)])

4


In [68]:
print(a.sum())

10


In [69]:
b = numpy.arange(6).reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [70]:
print(b.sum(axis=0))

[3 5 7]


In [71]:
print(b.sum(axis=1))

[ 3 12]


In [72]:
print(b.sum())

15


In [74]:
b0 = b.sum(axis=0, keepdims=True)
print(b0)

[[3 5 7]]


In [75]:
print(b0.shape)

(1, 3)


In [76]:
b1 = b.sum(axis=1,keepdims=True)

In [77]:
print(b1)

[[ 3]
 [12]]


In [78]:
print(b1.shape)

(2, 1)


In [79]:
a = numpy.array([4,3,1,4,2])
print(a)

[4 3 1 4 2]


In [80]:
print(numpy.sort(a))

[1 2 3 4 4]


In [81]:
print(numpy.argsort(a))

[2 4 1 0 3]
